name: 'Deployment Workflow'
on:
  push:
jobs:
  CleanupRuns:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  Modules:
    name: Modules
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
          lookup-only: true
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  Lint:
    name: Lint
    needs: Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Run lint
        run: yarn lint

  Test:
    name: Test
    needs: Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: test
        run: yarn test
